// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: token-validation.proto

package token_validation

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetUserDetailsByTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetUserDetailsByTokenRequest) Reset() {
	*x = GetUserDetailsByTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_validation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDetailsByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsByTokenRequest) ProtoMessage() {}

func (x *GetUserDetailsByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetUserDetailsByTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserDetailsByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserDetailsByTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserResourceProto `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserDetailsByTokenResponse) Reset() {
	*x = GetUserDetailsByTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_validation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDetailsByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsByTokenResponse) ProtoMessage() {}

func (x *GetUserDetailsByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetUserDetailsByTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserDetailsByTokenResponse) GetUser() *UserResourceProto {
	if x != nil {
		return x.User
	}
	return nil
}

type UserResourceProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64   `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname     string   `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Mail        string   `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	Username    string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password    string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Authorities []string `protobuf:"bytes,6,rep,name=authorities,proto3" json:"authorities,omitempty"`
}

func (x *UserResourceProto) Reset() {
	*x = UserResourceProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_validation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResourceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResourceProto) ProtoMessage() {}

func (x *UserResourceProto) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResourceProto.ProtoReflect.Descriptor instead.
func (*UserResourceProto) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{2}
}

func (x *UserResourceProto) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResourceProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResourceProto) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UserResourceProto) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserResourceProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResourceProto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserResourceProto) GetAuthorities() []string {
	if x != nil {
		return x.Authorities
	}
	return nil
}

var File_token_validation_proto protoreflect.FileDescriptor

var file_token_validation_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x79, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x58, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0xbf, 0x01, 0x0a, 0x11, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x32, 0x94, 0x01, 0x0a,
	0x16, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x2e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2f, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x14,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_token_validation_proto_rawDescOnce sync.Once
	file_token_validation_proto_rawDescData = file_token_validation_proto_rawDesc
)

func file_token_validation_proto_rawDescGZIP() []byte {
	file_token_validation_proto_rawDescOnce.Do(func() {
		file_token_validation_proto_rawDescData = protoimpl.X.CompressGZIP(file_token_validation_proto_rawDescData)
	})
	return file_token_validation_proto_rawDescData
}

var file_token_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_token_validation_proto_goTypes = []interface{}{
	(*GetUserDetailsByTokenRequest)(nil),  // 0: token_validation.GetUserDetailsByTokenRequest
	(*GetUserDetailsByTokenResponse)(nil), // 1: token_validation.GetUserDetailsByTokenResponse
	(*UserResourceProto)(nil),             // 2: token_validation.UserResourceProto
}
var file_token_validation_proto_depIdxs = []int32{
	2, // 0: token_validation.GetUserDetailsByTokenResponse.user:type_name -> token_validation.UserResourceProto
	0, // 1: token_validation.TokenValidationService.GetUserDetailsByToken:input_type -> token_validation.GetUserDetailsByTokenRequest
	1, // 2: token_validation.TokenValidationService.GetUserDetailsByToken:output_type -> token_validation.GetUserDetailsByTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_token_validation_proto_init() }
func file_token_validation_proto_init() {
	if File_token_validation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_token_validation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDetailsByTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_validation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDetailsByTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_validation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResourceProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token_validation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_validation_proto_goTypes,
		DependencyIndexes: file_token_validation_proto_depIdxs,
		MessageInfos:      file_token_validation_proto_msgTypes,
	}.Build()
	File_token_validation_proto = out.File
	file_token_validation_proto_rawDesc = nil
	file_token_validation_proto_goTypes = nil
	file_token_validation_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TokenValidationServiceClient is the client API for TokenValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenValidationServiceClient interface {
	GetUserDetailsByToken(ctx context.Context, in *GetUserDetailsByTokenRequest, opts ...grpc.CallOption) (*GetUserDetailsByTokenResponse, error)
}

type tokenValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenValidationServiceClient(cc grpc.ClientConnInterface) TokenValidationServiceClient {
	return &tokenValidationServiceClient{cc}
}

func (c *tokenValidationServiceClient) GetUserDetailsByToken(ctx context.Context, in *GetUserDetailsByTokenRequest, opts ...grpc.CallOption) (*GetUserDetailsByTokenResponse, error) {
	out := new(GetUserDetailsByTokenResponse)
	err := c.cc.Invoke(ctx, "/token_validation.TokenValidationService/GetUserDetailsByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenValidationServiceServer is the server API for TokenValidationService service.
type TokenValidationServiceServer interface {
	GetUserDetailsByToken(context.Context, *GetUserDetailsByTokenRequest) (*GetUserDetailsByTokenResponse, error)
}

// UnimplementedTokenValidationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTokenValidationServiceServer struct {
}

func (*UnimplementedTokenValidationServiceServer) GetUserDetailsByToken(context.Context, *GetUserDetailsByTokenRequest) (*GetUserDetailsByTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetailsByToken not implemented")
}

func RegisterTokenValidationServiceServer(s *grpc.Server, srv TokenValidationServiceServer) {
	s.RegisterService(&_TokenValidationService_serviceDesc, srv)
}

func _TokenValidationService_GetUserDetailsByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailsByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenValidationServiceServer).GetUserDetailsByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token_validation.TokenValidationService/GetUserDetailsByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenValidationServiceServer).GetUserDetailsByToken(ctx, req.(*GetUserDetailsByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenValidationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "token_validation.TokenValidationService",
	HandlerType: (*TokenValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserDetailsByToken",
			Handler:    _TokenValidationService_GetUserDetailsByToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token-validation.proto",
}
